### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_slave'

### ISSUE THREAD

**Issue by Emiller00** [wuhuikai/FastFCN#10]
Hi!
I am not sure what is causing the following Error although I worry my cuda version is wrong or my gpu could not be suitable. 

I am running cuda 10 on a 1060 GTX

When I run 

```
#train
CUDA_VISIBLE_DEVICES=0 python train.py --dataset pcontext \
    --model encnet --jpu --aux --se-loss \
    --backbone resnet50 --checkname encnet_res50_pcontext
```

I get 
```
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    trainer.training(epoch)
  File "train.py", line 110, in training
    outputs = self.model(image)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/encoding/models/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/encoding/models/base.py", line 55, in base_forward
    x = self.pretrained.conv1(x)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/emiller/WorkPlace/DataScience/Personal/venv/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 58, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

```

At first i thought this is because i am not multi gpu but could it be something else?

**Comment by wuhuikai** [comment]
You're right. The reason is that you're not using multiple GPUs. Change `SynBN` to regular `BN` if you want to train on one GPU.
