### ISSUE TITLE
I can't successfully run train script on my dataset.

### ISSUE THREAD

**Issue by artem-bondarenko-ua** [wuhuikai/FastFCN#103]
I took the code of ade20 dataset as a basis and changed the paths to my dataset.
At first, the masks were in png format (24 bits). I thought that this was the problem (I compared the formats of the ade20 masks and mine). Got an error:
```
/usr/bin/python3.8 /home/a.sysa/Videos/FastFCN/experiments/segmentation/train.py --dataset brain-tumor --model fcn --jpu JPU --no-cuda --backbone resnet50
Namespace(aux=False, aux_weight=0.2, backbone='resnet50', base_size=520, batch_size=16, checkname='default', crop_size=480, cuda=False, dataset='brain-tumor', dilated=False, epochs=120, ft=False, jpu='JPU', lateral=False, lr=0.01, lr_scheduler='poly', mode='testval', model='fcn', model_zoo=None, momentum=0.9, ms=False, no_cuda=True, no_val=False, resume=None, save_folder='experiments/segmentation/results', se_loss=False, se_weight=0.2, seed=1, split='val', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
BaseDataset: base_size 520, crop_size 480
len(img_paths): 178
Using poly LR Scheduler!
Starting Epoch: `0`
Total Epoches: 120
  0%|          | 0/11 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0100,                 previous best = 0.0000
/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
  0%|          | 0/11 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "/home/a.sysa/Videos/FastFCN/experiments/segmentation/train.py", line 217, in <module>
    trainer.training(epoch)
  File "/home/a.sysa/Videos/FastFCN/experiments/segmentation/train.py", line 141, in training
    loss = self.criterion(*outputs, target)
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/a.sysa/Videos/FastFCN/encoding/nn/customize.py", line 39, in forward
    return super(SegmentationLosses, self).forward(*inputs)
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1120, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

```

Then I changed the mask format to png (8 bits) and now I get the following error

```
Namespace(aux=False, aux_weight=0.2, backbone='resnet50', base_size=520, batch_size=16, checkname='default', crop_size=480, cuda=False, dataset='brain-tumor', dilated=False, epochs=120, ft=False, jpu='JPU', lateral=False, lr=0.01, lr_scheduler='poly', mode='testval', model='fcn', model_zoo=None, momentum=0.9, ms=False, no_cuda=True, no_val=False, resume=None, save_folder='experiments/segmentation/results', se_loss=False, se_weight=0.2, seed=1, split='val', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
BaseDataset: base_size 520, crop_size 480
len(img_paths): 178
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 120
  0%|          | 0/11 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0100,                 previous best = 0.0000
/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
  0%|          | 0/11 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "/home/a.sysa/Videos/FastFCN/experiments/segmentation/train.py", line 217, in <module>
    trainer.training(epoch)
  File "/home/a.sysa/Videos/FastFCN/experiments/segmentation/train.py", line 141, in training
    loss = self.criterion(*outputs, target)
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/a.sysa/Videos/FastFCN/encoding/nn/customize.py", line 39, in forward
    return super(SegmentationLosses, self).forward(*inputs)
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1120, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/a.sysa/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 254 is out of bounds.

Process finished with exit code 1

```

I run it without using CUDA on the CPU. (to run the code ш  followed some advice from closed issues)

**Comment by wuhuikai** [comment]
As it said, `Target 254 is out of bounds`. The label image should only contain 0 - [C-1], where C is the number of classes, besides a number that indicates ignorance.
