### ISSUE TITLE
RuntimeError: => no checkpoint found at 'encnet_jpu_res50_pcontext.pth.tar'

### ISSUE THREAD

**Issue by biter0088** [wuhuikai/FastFCN#109]
Besides,after I download encnet_jpu_res50_pcontext.pth.tar,I can't unrar it

(yolov5py37) meng@meng:~/deeplearning/FastFCN$ 
>     CUDA_VISIBLE_DEVICES=0,1,2,3 python -m experiments.segmentation.test --dataset pcontext \
>     --model encnet --jpu JPU --aux --se-loss \
>     --backbone resnet50 --resume encnet_jpu_res50_pcontext.pth.tar --split val --mode testval
Namespace(aux=True, aux_weight=0.2, backbone='resnet50', base_size=520, batch_size=16, checkname='default', crop_size=480, cuda=True, dataset='pcontext', dilated=False, epochs=80, ft=False, jpu='JPU', lateral=False, lr=0.001, lr_scheduler='poly', mode='testval', model='encnet', model_zoo=None, momentum=0.9, ms=False, no_cuda=False, no_val=False, resume='encnet_jpu_res50_pcontext.pth.tar', save_folder='experiments/segmentation/results', se_loss=True, se_weight=0.2, seed=1, split='val', start_epoch=0, test_batch_size=16, train_split='train', weight_decay=0.0001, workers=16)
loading annotations into memory...
JSON root keys:dict_keys(['info', 'images', 'annos_segmentation', 'annos_occlusion', 'annos_boundary', 'categories', 'parts'])
Done (t=3.05s)
creating index...
index created! (t=2.40s)
mask_file: /home/meng/.encoding/data/VOCdevkit/VOC2010/val.pth
Traceback (most recent call last):
  File "/home/meng/anaconda3/envs/yolov5py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/meng/anaconda3/envs/yolov5py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/meng/deeplearning/FastFCN/experiments/segmentation/test.py", line 91, in <module>
    test(args)
  File "/home/meng/deeplearning/FastFCN/experiments/segmentation/test.py", line 54, in test
    raise RuntimeError("=> no checkpoint found at '{}'" .format(args.resume))
RuntimeError: => no checkpoint found at 'encnet_jpu_res50_pcontext.pth.tar'

**Comment by biter0088** [comment]
Put the 'encnet_jpu_res50_pcontext.pth.tar' into /home/meng/.encoding/models/
and enter like below

>CUDA_VISIBLE_DEVICES=0,1,2,3 python -m experiments.segmentation.test --dataset pcontext \
>    --model encnet --jpu JPU --aux --se-loss \
>  --backbone resnet50 --resume /home/meng/.encoding/models/encnet_jpu_res50_pcontext.pth.tar --split val --mode testval
