### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by aligoglos** [wuhuikai/FastFCN#13]
when I tried to run test.py I got this error:

```
C:\Users\127051\AppData\Local\Programs\Python\Python35\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 1388 --file "D:/Artificial Intelligence/Segmentation/SRC/FastFCN-master/FastFCN-master/experiments/segmentation/test.py"
pydev debugger: process 12360 is connecting

Connected to pydev debugger (build 191.6605.12)
C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for c++: Command 'c++' returned non-zero exit status 1
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Artificial Intelligence/Segmentation/SRC/FastFCN-master/FastFCN-master/experiments/segmentation/test.py", line 12, in <module>
    import encoding.utils as utils
  File "D:\Artificial Intelligence\Segmentation\SRC\FastFCN-master\FastFCN-master\experiments\segmentation\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "D:\Artificial Intelligence\Segmentation\SRC\FastFCN-master\FastFCN-master\experiments\segmentation\encoding\nn\__init__.py", line 12, in <module>
    from .syncbn import *
  File "D:\Artificial Intelligence\Segmentation\SRC\FastFCN-master\FastFCN-master\experiments\segmentation\encoding\nn\syncbn.py", line 23, in <module>
    from ..functions import *
  File "D:\Artificial Intelligence\Segmentation\SRC\FastFCN-master\FastFCN-master\experiments\segmentation\encoding\functions\__init__.py", line 2, in <module>
    from .syncbn import *
  File "D:\Artificial Intelligence\Segmentation\SRC\FastFCN-master\FastFCN-master\experiments\segmentation\encoding\functions\syncbn.py", line 13, in <module>
    from .. import lib
  File "D:\Artificial Intelligence\Segmentation\SRC\FastFCN-master\FastFCN-master\experiments\segmentation\encoding\lib\__init__.py", line 14, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\cpp_extension.py", line 645, in load
    is_python_module)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\cpp_extension.py", line 859, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\utils\cpp_extension.py", line 1064, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "C:\Users\127051\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1

Process finished with exit code -1
```
My environment :
torch : 1.0.1
os : windows 10
python 3.5.4

**Comment by wuhuikai** [comment]
The provided [ninja](https://github.com/wuhuikai/FastFCN/blob/master/ninja) is for `Linux`, try to replace it with the `Windows` version. **Warning**: The code may **not** support `Windows`. Only tested on `Ubuntu 16.04 LTS`.

**Comment by wuhuikai** [comment]
@aligoglos The code in branch `latest` is now ready, which uses official `SyncBatchNorm` and can run on all OS with `PyTorch>=1.1.0`.
