### ISSUE TITLE
Should we use Ninja,before "python scripts/prepare_ade20k.py"? Can you help me?Thank you!

### ISSUE THREAD

**Issue by Xjunjiang** [wuhuikai/FastFCN#17]
Traceback (most recent call last):
  File "scripts/prepare_ade20k.py", line 6, in <module>
    from encoding.utils import download, mkdir
  File "E:\PycharmProject\venv\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "E:\PycharmProject\venv\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .syncbn import *
  File "E:\PycharmProject\venv\lib\site-packages\encoding\nn\syncbn.py", line 23, in <module>
    from ..functions import *
  File "E:\PycharmProject\venv\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .syncbn import *
  File "E:\PycharmProject\venv\lib\site-packages\encoding\functions\syncbn.py", line 13, in <module>
    from .. import lib
  File "E:\PycharmProject\venv\lib\site-packages\encoding\lib\__init__.py", line 14, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "E:\PycharmProject\venv\lib\site-packages\torch\utils\cpp_extension.py", line 645, in load
    is_python_module)
  File "E:\PycharmProject\venv\lib\site-packages\torch\utils\cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "E:\PycharmProject\venv\lib\site-packages\torch\utils\cpp_extension.py", line 837, in _write_ninja_file_and_build
    verify_ninja_availability()
  File "E:\PycharmProject\venv\lib\site-packages\torch\utils\cpp_extension.py", line 875, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

**Comment by wuhuikai** [comment]
We have included `ninja` in the project. Can you run `ninja --version` in the root folder of the project?

**Comment by Xjunjiang** [comment]
> We have included `ninja` in the project. Can you run `ninja --version` in the root folder of the project?

It can't work, maybe because I use win10 system, thank you very much ! We will continue debugging

**Comment by wuhuikai** [comment]
Then you should install `ninja` in your system firstly.
