### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_slave'

### ISSUE THREAD

**Issue by hhhwww123** [wuhuikai/FastFCN#34]
Hi, thanks to help me solve the ninja issue.But, there is a new issue come:

/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 240
  0%|                                                                                                                                                                | 0/185 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0100,                 previous best = 0.0000
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    trainer.training(epoch)
  File "train.py", line 110, in training
    outputs = self.model(image)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/encoding/models/deeplabv3.py", line 22, in forward
    _, _, c3, c4 = self.base_forward(x)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/encoding/models/base.py", line 55, in base_forward
    x = self.pretrained.conv1(x)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 58, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

Can you tell me how to solve ??

**Comment by wuhuikai** [comment]
Please see #10 #12.
