### ISSUE TITLE
NVIDIA driver on your system is too old

### ISSUE THREAD

**Issue by hhhwww123** [wuhuikai/FastFCN#37]
Hi, can you tell me how to solve this problem:

Traceback (most recent call last):
  File "train.py", line 182, in <module>    trainer.validation(epoch)  File "train.py", line 149, in validation    correct, labeled, inter, union = eval_batch(self.model, image, target)
  File "train.py", line 134, in eval_batch    target = target.cuda()  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/cuda/__init__.py", line 178, in _lazy_init    _check_driver()
  File "/home/weizhaoxiang/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/cuda/__init__.py", line 108, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by wuhuikai** [comment]
```
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
```
