### ISSUE TITLE
Wrong when i run prepare_pcontext.py

### ISSUE THREAD

**Issue by Anikily** [wuhuikai/FastFCN#43]
[yulu@yq01-gpu-255-126-19-00 FastFCN]$ python scripts/prepare_pcontext.py
/home/yulu/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:166: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Traceback (most recent call last):
  File "scripts/prepare_pcontext.py", line 7, in <module>
    from encoding.utils import download, mkdir
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .syncbn import *
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/encoding/nn/syncbn.py", line 23, in <module>
    from ..functions import *
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .syncbn import *
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/encoding/functions/syncbn.py", line 13, in <module>
    from .. import lib
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/encoding/lib/__init__.py", line 14, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/yulu/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/yulu/anaconda3/lib/python3.7/subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/yulu/anaconda3/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/yulu/anaconda3/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

**Comment by Anikily** [comment]
pytorch==1.0
python3.5
