### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_slave'

### ISSUE THREAD

**Issue by neverstoplearn** [wuhuikai/FastFCN#59]
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    trainer.training(epoch)
  File "train.py", line 110, in training
    outputs = self.model(image)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../../encoding/models/deeplabv3.py", line 22, in forward
    _, _, c3, c4 = self.base_forward(x)
  File "../../encoding/models/base.py", line 55, in base_forward
    x = self.pretrained.conv1(x)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../../encoding/nn/syncbn.py", line 58, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

how can i fix it?

**Comment by ucb-pb** [comment]
what was the solution? Edit: Ok, I see this issue has been already raised by someone else.

**Comment by wuhuikai** [comment]
Please use multiple GPUs.
