### ISSUE TITLE
pytorch1.5出现死锁

### ISSUE THREAD

**Issue by LiouCZ** [wuhuikai/FastFCN#68]
在第一个epoch开始就卡住了，num_work设置为0也是一样

**Comment by wuhuikai** [comment]
请提供详细的系统配置和错误报告~

**Comment by LiouCZ** [comment]
> 请提供详细的系统配置和错误报告~

配置：3个k80 ubuntu18 cuda10.2 python3.6 pytorch1.5 
运行过程中没有报错，就是卡在第一个batch,没有进入model的训练，中断程序后出现以下提示：
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/zhangjp/lcz/FastFCN-master/experiments/segmentation/train.py", line 186, in <module>
    trainer.training(epoch)
  File "/home/ubuntu/zhangjp/lcz/FastFCN-master/experiments/segmentation/train.py", line 115, in training
    outputs = self.model(image)
  File "/home/ubuntu/.virtualenvs/zhangjp_cv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.virtualenvs/zhangjp_cv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/.virtualenvs/zhangjp_cv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/.virtualenvs/zhangjp_cv/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    thread.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by wuhuikai** [comment]
不知道可能的原因，而且我也没有环境可以复现上述配置。可以尝试使用`latest`分支~

**Comment by LiouCZ** [comment]
> 不知道可能的原因，而且我也没有环境可以复现上述配置。可以尝试使用`latest`分支~

谢谢您的回复
