### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by DancingJane** [wuhuikai/FastFCN#77]
I met this error when I train the model. I use the model psp or fcn and the backbone resnet50.  I use the latest branch. When I us the main branc ,the error is 
ValueError: not enough values to unpack (expected 4, got 2).
There is no such error when I train encnet model. What's wrong with the psp and fcn model? thank you.

the error of branch latest in detail is as follows:

Starting Epoch: 0
Total Epoches: 120
  0%|                                                                                                                                                                             | 0/10105 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0013,                 previous best = 0.0000

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Files/segmentation/FastFCN-latest/experiments/segmentation/train.py", line 217, in <module>
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/Files/segmentation/FastFCN-latest/experiments/segmentation/train.py", line 206, in main_worker
    trainer.training(epoch)
  File "/Files/segmentation/FastFCN-latest/experiments/segmentation/train.py", line 135, in training
    loss = self.criterion(outputs, target.cuda())
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/Files/segmentation/FastFCN-latest/encoding/nn/customize.py", line 53, in forward
    (pred1, se_pred, pred2), target = tuple(inputs)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by wuhuikai** [comment]
Can you provide the bash script that you train the model? I think maybe you turn `--se-loss` on.
